# Generated by Django 2.1.5 on 2019-01-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], max_length=1)),
                ('public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_sets', to='accounts.Account')),
            ],
        ),
        migrations.RenameModel(
            old_name='CardCategory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='cardset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_sets', to='cards.Category'),
        ),
        migrations.AddField(
            model_name='cardset',
            name='questions',
            field=models.ManyToManyField(to='cards.CardQuestion'),
        ),
    ]
