# Generated by Django 2.1.5 on 2019-02-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardset_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardquestion',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
